### ISSUE TITLE
YT downloader does not work

### ISSUE THREAD

**Issue by PHYT90DitYT** [Cobalt-Web/Cobalt#4]
Title says it all.
I have promptForDownloads on in my Chrome browser but I get "file not found."
I turned it off and.............
"file not found."

Discord phyt90dit #0.

**Comment by The-Rock-21** [comment]
I think that the creator of this project doesn't work on this anymore. I think that he is more focused on his new project which is called "Metallic".

**Comment by PHYT90DitYT** [comment]
Yeah, I saw. I'll try to get his attention on this one because it's so
amazing

**Comment by Nebelung-Dev** [comment]
Yeah I'm not really maintaining this anymore
