### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by The-Rock-21** [Cobalt-Web/Cobalt#6]
It crashes after using for a while
![Screenshot 2023-11-07 3 48 45 PM](https://github.com/cognetwork-dev/Cobalt/assets/101891804/1de38052-e0b7-44a8-afdf-2d5ff85e756f)

**Comment by The-Rock-21** [comment]
It seems to only crash when you are playing games. It crashes fast when I try to play games that take up a lot of resources.

**Comment by Nebelung-Dev** [comment]
Seems like an issue with the games then
